export const travels = [
  {
    name: "Rajdhani Express",
    departureDate: "2024-03-25",
    departureTime: "8:00 AM",
    arrivalDate: "2024-03-25",
    arrivalTime: "10:00 AM",
    sleeperDetails: "A/C Sleeper (2+1)",
    travelHours: "2 hr 10 min",
    price: "₹1500",
    seatsLeft: 10,
    windowsSeatsLeft: 5,
    rating: 4.5,
    totalRating: 100,
    departureCity: "Delhi",
    arrivalCity: "Mumbai",
    offerPrice: "₹2500",
  },
  {
    name: "Shatabdi Express",
    departureDate: "2024-03-26",
    departureTime: "10:00 AM",
    arrivalDate: "2024-03-26",
    arrivalTime: "12:00 PM",
    travelHours: "2 hr 10 min",
    price: "₹1200",
    seatsLeft: 15,
    windowsSeatsLeft: 7,
    rating: 4.3,
    totalRating: 80,
    sleeperDetails: "A/C Sleeper (2+1)",
    departureCity: "Mumbai",
    arrivalCity: "Bangalore",
    offerPrice: "₹2500",
  },
  {
    name: "Duronto Express",
    departureDate: "2024-03-27",
    departureTime: "12:00 PM",
    arrivalDate: "2024-03-27",
    arrivalTime: "2:00 PM",
    travelHours: "2 hr 10 min",
    price: "₹1000",
    seatsLeft: 8,
    windowsSeatsLeft: 4,
    rating: 4.8,
    totalRating: 120,
    sleeperDetails: "A/C Sleeper (2+1)",
    departureCity: "Bangalore",
    arrivalCity: "Chennai",
    offerPrice: "₹2500",
  },
  {
    name: "Garib Rath Express",
    departureDate: "2024-03-25",
    departureTime: "8:00 AM",
    arrivalDate: "2024-03-25",
    arrivalTime: "10:00 AM",
    sleeperDetails: "Sleeper (3+2)",
    travelHours: "2 hr 10 min",
    price: "₹800",
    seatsLeft: 10,
    windowsSeatsLeft: 5,
    rating: 4.2,
    totalRating: 90,
    departureCity: "Kolkata",
    arrivalCity: "Delhi",
    offerPrice: "₹2500",
  },
  {
    name: "Rajdhani Express",
    departureDate: "2024-03-26",
    departureTime: "10:00 AM",
    arrivalDate: "2024-03-26",
    arrivalTime: "12:00 PM",
    travelHours: "2 hr 10 min",
    price: "₹1500",
    seatsLeft: 15,
    windowsSeatsLeft: 7,
    rating: 4.6,
    totalRating: 95,
    sleeperDetails: "A/C Sleeper (2+1)",
    departureCity: "Delhi",
    arrivalCity: "Mumbai",
    offerPrice: "₹2500",
  },
  {
    name: "Shatabdi Express",
    departureDate: "2024-03-27",
    departureTime: "12:00 PM",
    arrivalDate: "2024-03-27",
    arrivalTime: "2:00 PM",
    travelHours: "2 hr 10 min",
    price: "₹1300",
    seatsLeft: 8,
    windowsSeatsLeft: 4,
    rating: 4.4,
    totalRating: 85,
    sleeperDetails: "A/C Sleeper (2+1)",
    departureCity: "Mumbai",
    arrivalCity: "Bangalore",
    offerPrice: "₹2500",
  },
  {
    name: "Duronto Express",
    departureDate: "2024-03-28",
    departureTime: "2:00 PM",
    arrivalDate: "2024-03-28",
    arrivalTime: "4:00 PM",
    travelHours: "2 hr 10 min",
    price: "₹1100",
    seatsLeft: 12,
    windowsSeatsLeft: 6,
    rating: 4.7,
    totalRating: 100,
    sleeperDetails: "A/C Sleeper (2+1)",
    departureCity: "Bangalore",
    arrivalCity: "Chennai",
    offerPrice: "₹2500",
  },
  {
    name: "Garib Rath Express",
    departureDate: "2024-03-29",
    departureTime: "4:00 PM",
    arrivalDate: "2024-03-29",
    arrivalTime: "6:00 PM",
    travelHours: "2 hr 10 min",
    price: "₹750",
    seatsLeft: 20,
    windowsSeatsLeft: 10,
    rating: 4.0,
    totalRating: 80,
    sleeperDetails: "Sleeper (3+2)",
    departureCity: "Chennai",
    arrivalCity: "Hyderabad",
    offerPrice: "₹2500",
  },
  {
    name: "Rajdhani Express",
    departureDate: "2024-03-30",
    departureTime: "6:00 PM",
    arrivalDate: "2024-03-30",
    arrivalTime: "8:00 PM",
    travelHours: "2 hr 10 min",
    price: "₹1600",
    seatsLeft: 18,
    windowsSeatsLeft: 9,
    rating: 4.8,
    totalRating: 110,
    sleeperDetails: "A/C Sleeper (2+1)",
    departureCity: "Hyderabad",
    arrivalCity: "Pune",
    offerPrice: "₹2500",
  },
  {
    name: "Shatabdi Express",
    departureDate: "2024-03-31",
    departureTime: "8:00 PM",
    arrivalDate: "2024-03-31",
    arrivalTime: "10:00 PM",
    travelHours: "2 hr 10 min",
    price: "₹1400",
    seatsLeft: 14,
    windowsSeatsLeft: 7,
    rating: 4.3,
    totalRating: 90,
    sleeperDetails: "A/C Sleeper (2+1)",
    departureCity: "Pune",
    arrivalCity: "Ahmedabad",
    offerPrice: "₹2500",
  },
];

export const pickup = [
  "Koyambedu, koyambedu",
  "MMDA, mmda",
  "Vadapalani, vadapalani",
  "Ashok Pillar, ashok pillar",
  "Ekkattuthangal, ekkatuthangal",
  "Alandur, alandur",
  "Shanthi Petrol Bunk, shanthi perol bunk",
  "Meenambakkam Airport, meenambakkam airport",
  "Pallavaram, pallavaram",
  "Chrompet, chrompet",
  "Tambaram, tamparam",
  "Koyambedu, koyambedu",
  "MMDA, mmda",
  "Vadapalani, vadapalani",
  "Ashok Pillar, ashok pillar",
  "Ekkattuthangal, ekkatuthangal",
  "Alandur, alandur",
  "Shanthi Petrol Bunk, shanthi perol bunk",
  "Meenambakkam Airport, meenambakkam airport",
  "Pallavaram, pallavaram",
  "Chrompet, chrompet",
  "Tambaram, tamparam",
  "Koyambedu, koyambedu",
  "MMDA, mmda",
  "Vadapalani, vadapalani",
  "Ashok Pillar, ashok pillar",
  "Ekkattuthangal, ekkatuthangal",
  "Alandur, alandur",
  "Shanthi Petrol Bunk, shanthi perol bunk",
  "Meenambakkam Airport, meenambakkam airport",
  "Pallavaram, pallavaram",
  "Chrompet, chrompet",
  "Tambaram, tamparam",
];

export const droppoint = [
  "Meenambakkam Airport, meenambakkam airport",
  "Pallavaram, pallavaram",
  "Chrompet, chrompet",
  "Tambaram, tamparam",
  "Koyambedu, koyambedu",
  "Ekkattuthangal, ekkatuthangal",
  "Alandur, alandur",
  "Shanthi Petrol Bunk, shanthi perol bunk",
  "MMDA, mmda",
  "Vadapalani, vadapalani",
  "Ashok Pillar, ashok pillar",
  "Koyambedu, koyambedu",
  "Ekkattuthangal, ekkatuthangal",
  "Alandur, alandur",
  "Shanthi Petrol Bunk, shanthi perol bunk",
  "MMDA, mmda",
  "Vadapalani",
];

export const reviews = [
  { stars: 5, percentage: 70 },
  { stars: 4, percentage: 17 },
  { stars: 3, percentage: 8 },
  { stars: 2, percentage: 4 },
  { stars: 1, percentage: 1 },
];
