

const TicketCard =
  [
    {
      id: 1,
      code: "Get Rs.1909 OFF on HO-JOY",
      path: require("../../asset/images/flight/airindia.png"),
      flightname: "Air India",
      flightid: "AI-654",
      deptime: "20:23",
      depfrom: "Chennai",
      fromstation: "Chennai International Airport,India",
      tostation: "Indira Gandhi International Airport,India",
      fromid: "MMA",
      traveltime: "2h:50m",
      returntime: "01:35",
      toid: "MUD",
      returnto: "Mumbai",
      seatleft: "18",
      price: "₹11,750",
      checkadultbaggage:"15Kg (Adult)",
      checkchildbaggage:"15 Kg (Child)",
      cabinadultbaggage:"7Kg (Adult)",
      cabinchildbaggage:"7Kg (Child)"
    },
    {
      id: 2,
      code: "Get Rs.1009 OFF on HO-JOY",
      path: require("../../asset/images/flight/vistara.jpg"),
      flightname: "Vistara",
      fromstation: "Chennai International Airport,India",
      tostation: "Indira Gandhi International Airport,India",
      flightid: "VI-704",
      deptime: "20:23",
      fromid: "MMA",
      depfrom: "Chennai",
      traveltime: "1h:10m",
      returntime: "01:35",
      toid: "CJT",
      returnto: "Coimbatore",
      seatleft: "7",
      price: "₹8,750",
      checkadultbaggage:"15Kg (Adult)",
      checkchildbaggage:"15 Kg (Child)",
      cabinadultbaggage:"7Kg (Adult)",
      cabinchildbaggage:"7Kg (Child)"
    },
    {
      id: 3,
      code: "Get Rs.1200 OFF on HO-JOY",
      path: require("../../asset/images/flight/indigo.jpg"),
      fromstation: "Chennai International Airport,India",
      tostation: "Indira Gandhi International Airport,India",
      flightname: "Indigo",
      flightid: "IN-504",
      deptime: "20:23",
      depfrom: "kochi",
      fromid: "KOA",
      traveltime: "3h:40m",
      returntime: "01:35",
      toid: "GOG",
      returnto: "Goa",
      seatleft: "10",
      price: "₹9,750",
      checkadultbaggage:"15Kg (Adult)",
      checkchildbaggage:"15 Kg (Child)",
      cabinadultbaggage:"7Kg (Adult)",
      cabinchildbaggage:"7Kg (Child)"
    },
    {
      id: 4,
      code: "Get Rs.109 OFF on HO-JOY",
      path: require("../../asset/images/flight/vistara.jpg"),
      fromstation: "Chennai International Airport,India",
      tostation: "Indira Gandhi International Airport,India",
      flightname: "Vistara",
      flightid: "VI-704",
      deptime: "20:23",
      depfrom: "Madurai",
      fromid: "MAD",
      traveltime: "1h:10m",
      returntime: "01:35",
      toid: "CJT",
      returnto: "Coimbatore",
      seatleft: "22",
      price: "₹5,750",
      checkadultbaggage:"15Kg (Adult)",
      checkchildbaggage:"15 Kg (Child)",
      cabinadultbaggage:"7Kg (Adult)",
      cabinchildbaggage:"7Kg (Child)"
    },
    {
      id: 5,
      code: "Get Rs.1009 OFF on HO-JOY",
      path: require("../../asset/images/flight/airindia.png"),
      fromstation: "Chennai International Airport,India",
      tostation: "Indira Gandhi International Airport,India",
      flightname: "Air India",
      flightid: "AI-124",
      deptime: "20:23",
      depfrom: "Chennai",
      fromid: "MMA",
      traveltime: "1h:10m",
      returntime: "01:35",
      returnto: "Delhi",
      toid: "DEL",
      seatleft: "25",
      price: "₹8,750",
      checkadultbaggage:"15Kg (Adult)",
      checkchildbaggage:"15 Kg (Child)",
      cabinadultbaggage:"7Kg (Adult)",
      cabinchildbaggage:"7Kg (Child)"
    },
    {
      id: 6,
      code: "Get Rs.1009 OFF on HO-JOY",
      path: require("../../asset/images/flight/indigo.jpg"),
      fromstation: "Chennai International Airport,India",
      tostation: "Indira Gandhi International Airport,India",
      flightname: "Indigo",
      flightid: "VI-704",
      deptime: "20:23",
      fromid: "MMA",
      depfrom: "Chennai",
      traveltime: "1h:10m",
      returntime: "01:35",
      toid: "CJT",
      returnto: "Coimbatore",
      seatleft: "13",
      price: "₹6,750",
      checkadultbaggage:"15Kg (Adult)",
      checkchildbaggage:"15 Kg (Child)",
      cabinadultbaggage:"7Kg (Adult)",
      cabinchildbaggage:"7Kg (Child)"
    },
    {
      id: 7,
      code: "Get Rs.1009 OFF on HO-JOY",
      path: require("../../asset/images/flight/vistara.jpg"),
      fromstation: "Chennai International Airport,India",
      tostation: "Indira Gandhi International Airport,India",
      flightname: "Vistara",
      flightid: "VI-704",
      deptime: "20:23",
      depfrom: "Chennai",
      traveltime: "1h:10m",
      returntime: "01:35",
      returnto: "Erode",
      seatleft: "15",
      price: "₹3,750",
      checkadultbaggage:"15Kg (Adult)",
      checkchildbaggage:"15 Kg (Child)",
      cabinadultbaggage:"7Kg (Adult)",
      cabinchildbaggage:"7Kg (Child)"
    },
  ]

export default TicketCard;