const BUS = {
  LOAD: "BUS_LOAD",
  LOAD_SUCCESS: "BUS_LOAD_SUCCESS",
  LOAD_FAIL: "BUS_LOAD_FAIL",
};

const BUSLAYOUT = {
  LOAD: "BUSLAYOUT_LOAD",
  LOAD_SUCCESS: "BUSLAYOUT_LOAD_SUCCESS",
  LOAD_FAIL: "BUSLAYOUT_LOAD_FAIL",
};

const BUSBOOK = {
  LOAD: "BUSBOOK_LOAD",
  LOAD_SUCCESS: "BUSBOOK_LOAD_SUCCESS",
  LOAD_FAIL: "BUSBOOK_LOAD_FAIL",
};

const BUSINFO = {
  LOAD: "BUSINFO_LOAD",
  LOAD_SUCCESS: "BUSINFO_LOAD_SUCCESS",
  LOAD_FAIL: "BUSINFO_LOAD_FAIL",
}

const BUSCITYLIST = {
  LOAD: "BUSCITYLIST_LOAD",
  LOAD_SUCCESS: "BUSCITYLIST_LOAD_SUCCESS",
  LOAD_FAIL: "BUSCITYLIST_LOAD_FAIL",
}


const CAR= {
  LOAD: "CAR_LOAD",
  LOAD_SUCCESS: "CAR_LOAD_SUCCESS",
  LOAD_FAIL: "CAR_LOAD_FAIL",
};

const CARBOOK = {
  LOAD: "CARBOOK_LOAD",
  LOAD_SUCCESS: "CARBOOK_LOAD_SUCCESS",
  LOAD_FAIL: "CARBOOK_LOAD_FAIL",
};

const FLIGHT_SEARCH = {
  LOAD_SEARCH: "LOAD_SEARCH",
  FLIGHTSEARCH_SUCCESS: "FLIGHTSEARCH_SUCCESS",
  FLIGHTSEARCH_FAIL: "FLIGHTSEARCH_FAIL",
};

const FLIGHTONEWAY = {
  LOAD: "FLIGHTONEWAY_LOAD",
  LOAD_SUCCESS: "FLIGHTONEWAY_LOAD_SUCCESS",
  LOAD_FAIL: "FLIGHTONEWAY_LOAD_FAIL",
};

const FLIGHTONEWAYINFO = {
  LOAD: "FLIGHTONEWAYINFO_LOAD",
  LOAD_SUCCESS: "FLIGHTONEWAYINFO_LOAD_SUCCESS",
  LOAD_FAIL: "FLIGHTONEWAYINFO_LOAD_FAIL",
};
const FLIGHTRETURNINFO = {
  LOAD: "FLIGHTRETURNINFO_LOAD",
  LOAD_SUCCESS: "FLIGHTRETURNINFO_LOAD_SUCCESS",
  LOAD_FAIL: "FLIGHTRETURNINFO_LOAD_FAIL",
};

const FLIGHTONEWAYBOOK = {
  LOAD: "FLIGHTONEWAYBOOK_LOAD",
  LOAD_SUCCESS: "FLIGHTONEWAYBOOK_LOAD_SUCCESS",
  LOAD_FAIL: "FLIGHTONEWAYBOOK_LOAD_FAIL",
};

const HOTEL_SEARCH = {
  HOTEL_LOAD: "HOTEL_LOAD",
  HOTELSEARCH_SUCCESS: "HOTELSEARCH_SUCCESS",
  HOTELSEARCH_FAIL: "HOTELSEARCH_FAIL",
};

const HOTEL_INFO = {
  LOAD_INFO: "LOAD_INFO",
  HOTELINFO_SUCCESS: "HOTELINFO_SUCCESS",
  HOTELINFO_FAIL: "HOTELINFO_FAIL",
};

const HOTEL_ROOM = {
  LOAD_ROOM:"LOAD_ROOM",
  HOTELROOM_SUCCESS: "HOTELROOM_SUCCESS",
  HOTELROOM_FAIL:"HOTELROOM_FAIL"
}

const BLOCK_ROOM = {
  LOAD_BLOCKROOM:"LOAD_BLOCKROOM",
  BLOCKROOM_SUCCESS: "BLOCKROOM_SUCCESS",
  BLOCKROOM_FAIL:"BLOCKROOM_FAIL"
}

const HOTEL_BOOK = {
  LOAD_HOTELBOOK:"LOAD_HOTELBOOK",
  HOTELBOOK_SUCCESS: "HOTELBOOK_SUCCESS",
  HOTELBOOK_FAIL:"HOTELBOOK_FAIL"
}

const HOTELCITYLIST = {
  LOAD_HOTELCITYLIST: "HOTELCITYLIST_LOAD",
  HOTELCITYLIST_SUCCESS: "HOTELCITYLIST_LOAD_SUCCESS",
  HOTELCITYLIST_FAIL: "HOTELCITYLIST_LOAD_FAIL",
}

const HOTEL_DESTINATION = {
  LOAD_HOTELDESTINATION: "HOTELDESTINATION_LOAD",
  HOTELDESTINATION_SUCCESS: "HOTELDESTINATION_SUCCESS",
  HOTELDESTINATION_FAIL: "HOTELDESTINATION_FAIL",
  
}

const CARCITYLIST = {
  LOAD_CARCITYLIST: "LOAD_CARCITYLIST",
  CARCITYLIST_SUCCESS:"CARCITYLIST_SUCCESS",
  CARCITYLIST_FAIL: "CARCITYLIST_FAIL",
}


const AIRPORTCITYLIST = {
  LOAD_AIRPORTCITYLIST: "AIRPORTCITYLIST_LOAD",
  AIRPORTCITYLIST_SUCCESS: "AIRPORTCITYLIST_LOAD_SUCCESS",
  AIRPORTCITYLIST_FAIL: "AIRPORTCITYLIST_LOAD_FAIL",
}

const AIRLINE = {
  LOAD_AIRLINE: "AIRLINE_LOAD",
  AIRLINE_SUCCESS: "AIRLINE_LOAD_SUCCESS",
  AIRLINE_FAIL: "AIRLINE_LOAD_FAIL",
}

const SIGNUP = {
  LOAD_SIGNUP: "LOAD_SIGNUP",
  SIGNUP_SUCCESS: "SIGNUP_LOAD_SUCCESS",
  SIGNUP_FAIL: "SIGNUP_LOAD_FAIL",
}

export const HOTELGUESTINFO = (data) =>{
  console.log("Inside guest ............................azction",data)
  return {type : "HOTEL_GUESTINFO",
  data
}
}

export {
  BUS,
  BUSINFO,
  BUSLAYOUT,
  BUSBOOK,
  BUSCITYLIST,
  CAR,
  CARBOOK,
  FLIGHT_SEARCH,
  FLIGHTONEWAY,
  FLIGHTONEWAYINFO,
  FLIGHTRETURNINFO,
  FLIGHTONEWAYBOOK,
  HOTEL_SEARCH,
  HOTEL_INFO,
  HOTEL_ROOM,
  BLOCK_ROOM,
  HOTEL_BOOK,
  HOTELCITYLIST,
  HOTEL_DESTINATION,
  CARCITYLIST,
  AIRPORTCITYLIST,
  AIRLINE,
  SIGNUP,
}

